version: "3.8"

services:
  nginx:
    image: nginx
    container_name: blog-nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql

  mysql:
    image: mysql:5.7
    container_name: blog-mysql
    restart: unless-stopped
    ports:
      - 33060:3306
    volumes:
      - ./storage/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: homestead
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: secret

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: blog-app
    volumes:
      - ./:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog-phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
  # node:
  #   container_name: node
  #   image: node:15.2.0-alpine3.10
  #   working_dir: /node_modules
  #   volumes:
  #     - ./:/node_modules
  #   command: "npm start"
